### ISSUE TITLE
include some benchmark results

### ISSUE THREAD

**Issue by jeffbski** [neoziro/recompact#48]
Since the README mentions that there is some improvements in performance over recompose, it would be nice to provide those in the README or at least in a linked document so people could see them without needing to install and run them for themselves. 

Knowing the relative scope of the performance improvement is key for people to know if that is a relevant factor.

**Comment by neoziro** [comment]
Benchmarks are not very significative, I have some isolation problems. Actually React + enzyme represents a big part of the run, reompact / recompose stack is a small part and it's difficult to have a relevant result. That's why I don't publish it yet. However I found that having a lot of higher-order doesn't truly involve performance problem. Help is welcome!

**Comment by jeffbski** [comment]
It sounded like you thought that performance was improved in some situations like update https://github.com/acdlite/recompose/pull/182#issuecomment-274460981

So you could elaborate on that or maybe one should not promote the performance in the README unless there is a way to prove it.

It is a clear benefit to have less components when viewing in dev tools.

**Comment by matthieuprat** [comment]
https://github.com/neoziro/recompact/tree/master/src/__benchmarks__

**Comment by jeffbski** [comment]
Fantastic!
